config/routes.rb
Ccwchen::Application.routes.draw do   get "comments/new"

  get "home/index"

  get "home/professional"

  get "home/education"

  get "home/personal"

  get "home/contact"
  
    get "home/products"
  
get "home/print"

match '/professional' => 'home#professional'
match '/personal' => 'home#personal'
match '/education' => 'home#education'

root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def professional
  end

  def education
  end

  def personal
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Christine Chen's Resume"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<% provide(:title, 'Contact Info') %>

<h3 class="page_title">Contact Info</h3>


<div class="main_content">

<table table class="table table-bordered">
<tr><th width="120">Email</th><td>	<a href="mailto:christine@ccwchen.com">
	christine@ccwchen.com</a></td></tr>
<tr><th>Phone</th><td>650.387.3524</td></tr>
<tr><th>Skype</th><td><a href="skype:kayakera?chat">kayakera</a></td></tr>
<tr><th>Web Site</th><td><a href="http://www.ccwchen.com">www.ccwchen.com</a> </td></tr>
</table>

</div>		

app/views/home/education.html.erb
<% provide(:title, 'Education') %>
<h3 class="page_title">Education</h3>
<div class="main_content">
<table table class="table table-bordered">
<tr>
	<td width="200">
		<b>Harvard Business School</b><br/>
		Boston, MA.</td>
	<td><b>Master of Business Administration</b></br>
	With concentrations in marketing and entrepreneurial business<br>
	Elected Treasurer, Asian Business Club</br>
	Selected admission counselor</p>
	</td>
</tr>

<tr>
	<td><b>Imperial College<br />University of London</b><br/>London, England.</td>
	<td><b>Bachelor of Information Systems Engineering</b></br>
	Double major in Computer Science, Electrical and Electronics Engineering
	</td>
</tr>

<tr>
	<td><b>Padworth College</b><br />
		Reading, England.</td>
	<td><b>Awarded Full Scholarship</br><a href="http://en.wikipedia.org/wiki/GCE_Advanced_Level">GCE A-Levels</a></b></br>
		Advanced Mathematics<br>
		Physics<br>
		Chemistry<br>
		Biology<br>
	</td>
</tr>

<tr>
	<td><b>Continental School</b><br />
		Jeddah, Saudi Arabia.</td>
	<td><b><a href="http://en.wikipedia.org/wiki/General_Certificate_of_Education">GCSE O-Levels</a></b><br />	English, Mathematics, Biology, Physics, Chemistry, Geography, French, History.</br>
		Gymnastics Team Capitan</br>
	</td>
</tr>

</table>
</div>

app/views/home/index.html.erb
<% provide(:title, 'Product Development and Marketing Professional') %>

<div class="main_content">

	  <div class="hero-unit">
		<h3>Product Development and Marketing Professional.</h3>
		<div  class="summary_content">
		<h5>Summary</h5><ul><li>Product Development and Marketing Professional with 12+ years experience in the consumer eCommerce space.</li>
	<li>Proven track record in launching and marketing products with focus on user acquisition and profitability.</li>
	<li>Seasoned expert in managing multiple concurrent projects with tight deadlines, varying priorities, budgets, teams.</li>
	<li>Solid technology background with hands on web development, user interaction design, and testing experiences.</li>
	<li>Highly motivated self-starter. Entrepreneur: founder and director of a profitable photo sticker business.</li></ul>

   		<h5>Aspiration</h5>Create products that change the way people use traditional everyday items and are also useful, fun, and easy to use.
		
		<h5>Objective</h5>Seeks challenging product development leadership position to make significant contributions in a dynamic, fast-paced company.
		</div>
	<br />

		<table >
			<tr class="summary_table_header">
				<th><a class="btn btn-primary btn-large" href="professional">Professional</a></th>
				<th><a class="btn btn-primary btn-large" href="education">Education</a></th>
				<th><a class="btn btn-primary btn-large" href="personal">Personal</a></th>
			</tr>
			<tr> <td height="10" colspan="3"></td></tr>
			<tr valign="top"  class="summary_content">
				<td><ul><li>Product Development and Business Strategy Consultant.</li>
		<li>Director, Marketing and Product Development, PicStickers.</li>
		<li>Sr. Group Product Manager, Partners, Shutterfly.</li>
		<li>Sr. Manager, Business and Product Development, BeVocal.</li><li>Sr. Associate, Investment Banking, Bankers Trust.</li></ul></td>
				
		<td><ul><li>Harvard Business School, Master in Business Administration.</li>
			<li>Imperial College, London, Computer Science and Engineering Double Major.</li>
			<li>Scholarship recipient.</li></ul></td>
				<td><ul><li>Web Application Development Hobbyist (HTML, Ruby on Rails, VXML).</li>
			<li>Multi-lingual world traveler.</li>
		<li>Competitive whitewater kayaker.</li></ul></td>
			</tr>
		</table>
      </div>




</div>

app/views/home/personal.html.erb
<% provide(:title, 'Personal Background') %>
<h3 class="page_title">Personal Background</h3>

<div class="main_content">
<table table class="table table-bordered">
	
<tr><th width="120">Background</th><td>US citizen. Born in Taiwan. Attended elementary school in Taipei, Taiwan and high school in Jeddah, Saudi Arabia.</br>
	Won 2-year full scholarship to <a href="http://en.wikipedia.org/wiki/Sixth_form_college" target="blank">sixth form college</a> in Reading, England.</br>
	Computer science and engineering double major at Imperial College, University of London.</br>
	Worked in investment banking in London, New York, and Hong Kong.</td></tr>
	
	
<tr><th>Skills</th><td>Web Development Hobbyist: Ruby, Rails, HTML, VXML, CSS, Git, ...etc.<br />Working knowledge of User Interaction Design (web and voice).</br>Proficient with Photoshop Elements.</td></tr>
<tr><th>Languages</th><td>Fluent in English and Mandarin Chinese.<br />Working knowledge of Cantonese.<br />Basic Spanish.</td></tr>
<tr><th>Sports</th><td>Competitive Whitewater Kayaker.<br />Regular Yoga Practitioner.<br />Occasional biker, hiker, and runner.</td></tr>
<tr><th>Other Interests</th><td>Avid Reader.<br />Aspiring writer and cook.</td></tr>
</table>
</div>

app/views/home/products.html.erb
<% provide(:title, 'Product Portfolio') %>

<h3 class="page_title">Product Portfolio</h3>


<div class="main_content">

<table table class="table table-bordered">

<tr>
<th width="50" rowspan="2">Retail</th>
<td><b>Target Photo</b></br>
<li>Order prints on Shutterfly website for pickup at Target retail stores nationwide.</li>
<li>Shutterfly Prepaid Products sold in Target Stores: photo books, calendars, greeting cards, note cards, Shutterfly gift certificates.</li></td>
<td width="100"><a href="http://targetphoto.shutterfly.com" target="_blank"><img border="0" src="http://www.ccwchen.com/images/targetlogo.gif" width="150"/></a></td>
</tr>

<tr>
<td>	<b>Shutterfly Photo Kiosk</b></br>
	<li>Upload photos to Shutterfly web site.</li>
	<li>Order prints and photo cards for immediate printing at the kiosk.</li><li>Order prints, photo cards, and other photo gifts (e.g. T-shirts, Key chains, and Mugs) for shipping to home.</li></td>
<td><a href="http://share.shutterfly.com/action/welcome?sid=0AcsWLhwzatGLV7g" target="_blank"><img border="0" src="http://www.ccwchen.com/images/sflykiosk.jpg"/></a></td>
</tr>

<tr>
<th rowspan="2"><b>User Migrations</b></th>
<td><b>Yahoo! Photo</b><li>Migration of Yahoo! Photo users and images to Shutterfly.</li></td>
<td><img border="0" src="http://www.ccwchen.com/images/yahoologo.bmp" width="150"/></td>
</tr>

<tr>
<td><b>Sony ImageStation</b><li>Migration of Sony ImageStation users and images to Shutterfly.</li></td>
<td><img border="0" src="http://www.ccwchen.com/images/sonylogo.bmp" width="150"/></td>
</tr>

<tr>
<th rowspan="2"><b>Reward Programs</b></th>
<td><b>Delta SkyMiles and Northwest World Perks Mileage Programs</b><li>Customers earn mileage points with qualifying Shutterfly orders.</li></td>
<td><a href="http://www.shutterfly.com/delta" target="_blank"><img border="0" src="http://www.ccwchen.com/images/deltalogo.jpg"/></a></td>
</tr>


<tr>
<td><b>Web Loyalty Reservation Rewards</b><br /><li>Customers earn cash back on qualifying Shutterfly orders.</li></th>
<td><img border="0" src="http://www.ccwchen.com/images/wl_logo.png"/></a></td>
</tr>



<tr>
<th>Desktop Software</th>
<td><b>Adobe Photoshop Elements</b></br>
<li>Order Prints, Posters, Calendars, Photo Books, and Greeting Cards from Shutterfly directly on Photoshop Elements.</li>
<li>Upload photos from desktop to Shutterfly via Photoshop Elements.</li></td>
<td><img border="0" src="http://www.ccwchen.com/images/adobe2.png"/></br><img border="0" src="http://www.ccwchen.com/images/adobe.png"/></a></td>
</tr>



<tr>
<th rowspan="3">Social Media</th>
<td><b>Facebook</b></br><li>Pilot Shutterfly Photo Book application on Facebook.</li><li>Auto create a virtual photo book from user's Facebook photos.</li></td>
<td><a href="http://www.facebook.com/" target="_blank"><img border="0" src="http://www.ccwchen.com/images/fblogo.png"/></a></td>
</tr>

<tr>
<td><b>Flickr</b></br><li>Designed integration with Flickr for ordering prints and creating Shutterfly products.</li></td>
<td><a href="http://www.flickr.com" target="_blank"><img border="0" src="http://www.ccwchen.com/images/flickrlogo.png"/></a></td>
</tr>

<tr>
<td><b>Photo Contests</b></br><li>In-house and partner sponsored contests.</li></td>
<td><a href="http://www.shutterfly.com/contest" target="_blank"><img border="0" src="http://www.ccwchen.com/images/contest.jpg"/></a></td>
</tr>


<tr>
<th rowspan="3">Image Services</th>
<td><b>Custom Framing</b><li>Create and order custom frames for customer's Shutterfly photos.</li><li>Integrated with Art.com's framing studio.</li></td>
<td><a href="http://www.art.com"  target="_blank"><img border="0" src="http://www.ccwchen.com/images/artlogo.gif"/></a></td>
</tr>

<tr>
<td><b>Digital Picture Frame</b><li>Pre-load customer's Shutterfly photos onto the digital picture frame.</li></td>
<td><a href="http://www.pandigital.net/"  target="_blank"><img border="0" src="http://www.ccwchen.com/images/pandigital_logo.png"/></a></td>
</tr>

<tr>
<td><b>Scanning and Restoration</b><li>Upload customer's scanned or restored images to customer's Shutterfly account.</li></td>
<td><a href="http://www.scancafe.com"  target="_blank"><img border="0" src="http://www.ccwchen.com/images/scancafelogo.png"/></a></td>
</tr>

<tr>
<th rowspan="3">eCommerce</th>
<td><b>PayPal</b><li>Integrate PayPal as an additional payment method.</td>
<td><a href="http://www.paypal.com"  target="_blank"><img width="150" border="0" src="http://www.ccwchen.com/images/paypal_logo.gif"/></a></td>
</tr>

<tr>
<td><b>Customer Relationship Management (CRM)</b><li>Build tools to capture customer data (e.g. birth date, interests, and gifting occasions.).</li><li>Develop tools to enable user and order content driven targeted promotions with goal to accelerate next contact event or purchase cycle.</li></td>
<td><a href="http://www.shutterfly.com"  target="_blank"><img border="0" width="150" src="http://www.ccwchen.com/images/crm.jpg"/></td>
</tr>

<tr>
<td>	<b>Shutterfly Professional Photographers' Gallery Marketplace</b><li>A subscription based platform that enable photographers to sell prints and other photo products at their own prices and offer discounts of their choice.</li>
	<li>Launched new download product that allow photographers to sell digital copy of their photos.</li></td>
<td><a href="http://www.shutterfly.com/selling_photos_online/professional_photography.jsp" target="_blank"><img border="0" src="http://www.ccwchen.com/images/progal.png"/></a></td>
</tr>


<tr>
<th rowspan="2">Mobile Applications</th>
<td><b>Shutterfly iPhone Application</b>
<li>Upload, view, and share photos from the iPhone.</li>
<li>From prototype to launch and follow on releases.</li></td>
<td><a href="http://itunes.apple.com/us/app/shutterfly-for-iphone/id309465525?mt=8"  target="_blank"><img border="0" src="http://www.ccwchen.com/images/sflyiphonelogo.png"/></a></td>
</tr>

<tr>
<td><b>Wink | from Shutterfly</b><li>Create and order photo strips from the iPhone.</li><li>Integrated the Wink application to enable user to access their photos in their Shutterfly account.</li></td>
<td><a href="http://itunes.apple.com/us/app/id338742405?mt=8"  target="_blank"><img border="0" src="http://www.ccwchen.com/images/winklogo.png"/></a></td>
</tr>

<tr>
<th>Partner Integration Scalablity</th>
<td><b>Shutterfly Open APIs</b><li>Open API developer platform.</li><li>APIs that allow upload and access to Shutterfly photos and place orders for prints and select photo products.</li></br><u>Example of partners' implementation of Shutterfly Open APIs</u><li>PixMatter iPhone app</li><li>Pixelpipe web site and iPhone app</li><li>Eye-fi memory cards</li><li>Aurora desktop software</li><li>Adobe Lightroom 2 plug in</li></td>
<td><a href="http://www.shutterfly.com/developer" target="_blank"><img border="0" src="http://www.ccwchen.com/images/openfly.png" width="150" /></a></td>
</tr>


</table>

<a href="#pagetop">Go to top</a>
</div>		

app/views/home/professional.html.erb
<% provide(:title, 'Professional Experience') %>
<h3 class="page_title">Professional Experience</h3>




<div class="main_content">
<table table class="table table-bordered">

<!-- Consulting -->
<tr>
<th width="60">2010 to Present</th>
<td><b>Product Development and Business Strategy Consulting</b><br />Develop product strategy and implementation plan for clients in the consumer eCommerce domain.<br />
	<ul>
		<li>Prototype Development for an educational application for teaching children basic financial knowledge (e.g. the power of compounding.</li>
		<li>Providing website re-design feedback focusing on improving user experience to an online technical education company.</li>
		<li>Consulted with El Dorado County on implementing a shuttle bus service operating the South Fork American River Corridor. Created business case, implementation plan, and marketing strategy. Designed automated ticket sales  and reservation system through a dedicated website and on-board mobile device. Service launching in summer, 2013.</li>
	  <li>Developed a new products proposal and social media marketing strategy for a user generated fashion content company. 
	  <li>Consulted with a personalize party favor company to bring their merchandises online.</li>
	  <li>Created a proposal to revamp a baby products company's eCommerce website to improve user-interface, conversion rate, and profitability.</li>
	</ul></td>
<td width="100">Los Altos Hills, and Lotus, CA.</td>
</tr>

<!-- PicStickers -->
<tr>
<th>2009 to 2012</th>
<td><a href="http://www.picstickers.com" target="_blank"><img border="0" src="http://www.ccwchen.com/images/pxlogo.jpg"/></a></br>A privately held company founded in 2009. Produces custom photo stickers products.<br />
	<b>Director, Marketing & Product Development</b>
	<ul>
	  <li>From concept to launch and on-going growth: designed, developed, and launched company web site and products. 
	  <li>Responsible for product development and marketing with emphasis on new customer acquisition.</li>
	<li>Business acquired by a personalize stationery company in 2012.</li>
	</ul>	
</td>
<td>Los Altos Hills, CA.</td>
</tr>
<!-- Shutterfly -->
<tr>
<th>2007 to 2010</th>
<td><a href="http://www.shutterfly.com" target="_blank"><img border="0" src="http://www.ccwchen.com/images/sflylogo.gif"/></a></br>The leading Internet social expression and personal publishing service.<br/><b>Sr. Group Product Manager</b></br>
<ul><li>Responsible for all partner products development and integrations with primary objective of user acquisition.</li>
  <li>Oversee entire product management lifecycle.</li>
<li>Manage partner team of 3 engineers and 5 partner account managers.</li>
<li>Championed Shutterfly's API Platform, iPhone Apps, and, social media marketing on Facebook and other websites.</li></ul>

<u>Strategy and Discovery</u>
<ul><li>Identify, Assess, and, Champion new product opportunities. Collaborate with Business Development and Partners to evaluate new product opportunities, target audience, and, competitive landscape.</li>
  <li>Create high-level product spec including user interaction wireframe, workflow diagram, scope estimate, resource requirement, and ROI analysis.</li>
<li>Perform product feature discovery. Build and test prototype. Conduct usability interviews and testing.</li>
</ul>

<u>Implemenation and Launch</u>
<ul><li>Lead product implementation: determine and write final product requirement spec (including back-end data and finance reporting needs) and implementation schedule.</li>
<li>Co-ordinate cross-functional development team: UI, engineering, QA, Marketing, Data Reporting, Finance, Customer Support, PR, external integration partners/vendors.</li>
<li>Work with Marketing on go-to-market plan.</li>
<li>Make new product review presentation to Execute Team (CEO, CMO, VPs, etc.) and new product release customer support training.</li>
</ul>

<u>Post Launch Management</u>
<ul><li>Monitor and communicate product performance to key stakeholders including execute team and external partners. Created Partner Dashboard showing key success metrics: $revenue, $average selling prices, #orders, etc.</li>
<li>Drive product feature enhancements to improve usability and profitability. Phased feature release schedule utilizing a/b testing to determine feature success.</li>
<li>Manage product roadmap: prioritize release schedule and manage engineering resource utilization against contractual commitments.</li>
<li>Hold weekly partner team meeting for existing product performance review, current project implementation status, resource utilization plan, and evaluate prospective projects.</li>
</ul><br />
<p><a class="btn btn-primary btn-large" href="products">Product Portfolio</a></p></td>
<td>Redwood City, CA.</td>
</tr>
<!-- BeVocal -->
<tr>
<th>2000 to 2006</th>
<td><b>BeVocal</b> (acquired by <a href="http://www.nuance.com" target="_blank">Nuance</a>)</br>
Leading provider of next-generation automated customer self-service solutions. Major customers include: Cingular Wireless, MetroPCS, Liberty Wireless, Virgin Mobile, and ADP Dealer Services.<br />	<b>Sr. Manager, Business Development and Product Management</b></p>
	<b><u>Product Management and Marketing</u></b></br>
	<li>Developed and deployed voice application products for major US Wireless Carrier customers (<a href="http://www.wireless.att.com/learn/basics/choosing-features-services/voiceinfo.jsp" target="blank">AT&T VoiceInfo</a>) and an Enterprise customer's CRM system (dealer service appointment scheduler).
	</li>
	<li>Performed market and competitive analyses. Build business cases and pricing models. Define product strategy. Write Product and Marketing Requirement Documents (PRD and MRD). Work with engineering to build and deploy products.
	</li>
	<li>Work with customers to develop consumer marketing strategies to launch new products and increase existing product usage and market penetration. </li></ul></p>

	<b><u>Business Development</u></b></br>
	<li>Responsible for formulating strategies, developing and managing partnerships to generate new business.</li>
	<li>Analyze and identify new business opportunities. Source and evaluate partners. Negotiate business terms (e.g. co-branding terms, joint marketing budget, licensing rights, and pricing/revenue share).
	</li>
	<li>Manage the company's entire portfolio of third-party content for the VoComm  product. Responsible for developing new content partnerships, managing existing partner issues, developing and executing co-marketing programs.
	</li>
	<li>Worked on strategic partnering deals including: Strategic Alliance Agreement with BellSouth; and Joint Marketing Agreement with SUN Microsystems.
	</li>
	<li>Represent company at tradeshows, conferences and promotional events.</li></ul></p>

	<b><u>Others</u></b>
	<li>Financial forecasting and reporting. Assisted company head-count and budget planning.
	</li>
	<li>Developed sales proposals, pricing analyses, and presentations. Proposals resulted in several customer wins. 
	</li>
	<li>Supported fund raising and sale of a business division. Built valuation models. Participated in due diligence. 
	</li></br></td>
<td>Mountain View, CA.</td>
</tr>
<!-- Bankers -->
<tr>
<th>1996 to 1998</th>
<td><b>Bankers Trust Company</b> (acquired by <a href="http://www.db.com" target="_blank">Deutsche Bank</a>)<br /><b>Sr. Associate, Investment Banking</b></br>
<li>Executed various debt and equity-linked (convertible bonds) security issuances.</li>
<li>Involved in deal origination, conducted due diligence, developed financial models, and drafted offering documents.</li>
<li>Managed sales process: prepared road show sales material, press release, and investor presentations.</li></br></td>
<td>Hong Kong</td>
</tr>
<!-- SCB -->
<tr>
<th>1994 to 1996</th>
<td><a href="http://www.standardchartered.com" target="_blank"><b>Standard Chartered Bank</b></a><br /><b>Financial Analyst, Investment Banking</b></br>
<li>Executed issuances of debt securities  (bonds, notes, loans). Transaction size ranged from US$50 to US$150 million.</li>
<li>Assisted in the private placement in the US market for Asian companies debt issues.</li>
<li>Portfolio management. Monitored asset value in secondary market. Assisted in liquidating under performing assets.</li></br>
<b>Assistant Manager, Treasury</b></br>
<li>Marketed currency and interest rate products to corporations, financial institutions, and private investors. P&L responsibility of US$3 million.</li>
<li>Launched a new currency option linked deposit product. Designed marketing collaterals, sales training material, and administrative procedures.</li></br></td>
<td>London, New York, and Hong Kong.</td>
</tr>

</table>



<a href="#pagetop">Go to top</a>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	  <link href="css/bootstrap.min.css" rel="stylesheet" />
      <link rel="stylesheet" type="text/css" href="ccwstyle.css" />
</head>
<a name="pagetop"></a>
<body class = "container">

<div class="body_container">
	
	<header><!-- Global Header -->
		<div class="header_global">
			<div class="header_title"><%= image_tag "cclogo.jpg" %></div>
			<div class="header_nav">| <%= link_to 'Summary', home_index_path %> | <%= link_to 'Professional', home_professional_path %> | <%= link_to 'Portfolio', home_products_path %> | <%= link_to 'Education', home_education_path %> | <%= link_to 'Personal', home_personal_path %> | <%= link_to 'Contact', home_contact_path %>  | <%= link_to 'Printable Resume', "/resources/resume_cchen.pdf" %> |</div>
		</div>
	</header>
	
	
	

<%= yield %>


	

    <footer><!-- Global Footer -->
		<div class="footer_global">
			<div class="footer_nav">| <%= link_to 'Summary', home_index_path %> | <%= link_to 'Professional', home_professional_path %> | <%= link_to 'Portfolio', home_products_path %> | <%= link_to 'Education', home_education_path %> | <%= link_to 'Personal', home_personal_path %> | <%= link_to 'Contact', home_contact_path %>  | <%= link_to 'Printable Resume', "/resources/resume_cchen.pdf" %> |<br /><span class="footer_text">This resume website is built with Ruby on Rails by Christine Chen and deployed through Github and Heroku.</div>
		</div>
    </footer>


</div>
</body>
</html>